# Generated by Django 2.2.5 on 2019-10-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzc', '0002_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='gender',
        ),
    ]
